version: '3'
services:
  nest-backend:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rust-backend
  rust-backend:
    build:
      context: /submodules/nnn-rust-backend/.
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
